version: '3.7'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-prod
  #   tty: true
  #   stdin_open: true
  #   # yarnを使って起動しないためにここでenvを設定 
  #   # https://github.com/goldbergyoni/nodebestpractices/blob/6f6acbccb78402594e654b79f689e8537964cb95/sections/docker/bootstrap-using-node.md
  #   env_file:
  #     - .env.production
  #   working_dir: /app
  #   depends_on:
  #     - mysql
  #   ports:
  #     - '3000:3000'
  #   command: ["node", "dist/src/main"]
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile-dev
  #   tty: true
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #     - node_modules_volume:/app/node_modules
  #   command: ["yarn", "nodemon", "--watch", "src", "--ext", "ts", "dist/src/main"]

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'

volumes:
  # node_modules_volume:
  mysql-data:
    driver: local
